
spring:
  application:
    name: school-organization-service
  datasource:
    url: jdbc:postgresql://organization-db:5432/organization-db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"